# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e36c84842c4790460deec01ec3f0d41c539fc6a843a9dcaf739b6bc6fbb63f63027ff496f19c4b2f6ff2e2dbfd9f1d31f49d981ea33b36ce413ac06ffded630

test:
  secret_key_base: 07d95f81d3082429db97de9c7b5c72d6f8641e44c85ea256584420aa5a78b84553af5f696a3789f7de6c9b26b54ad4855e7bca726e3343b5bb0906238511dc24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
